name: tiny-xcp-home
datacenter: sultan
environment: development
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: xenserver
  linuxDistribution: ubuntu
  linuxVersion: 20.04.latest
  vmHostUsername: $<<XENSERVER_USERNAME>>
  vmHostPassword: $<<XENSERVER_PASSWORD>>
  vmNamePrefix: jeff
  vmHosts:
  - name: XCP-HOME
    address: 10.0.0.5
  xenServer:
     snapshot: true
network:
  premiseSubnet: 10.0.0.0/16
  nodesSubnet: 10.0.0.0/16
nodeOptions:
   upgrade: none
   passwordLength: 20
nodes:
   master-0:
     role: master
     privateAddress: 10.0.1.30
     vmHost: XCP-HOME
     vmProcessors: 4
     vmMemory: 2GiB
     vmDisk: 10GiB
