# Default values for m3db-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

isolationGroups: []

containerResources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

volumeResources:
  requests:
    storage: 1Gi
  limits:
    storage: 1Gi

replicationFactor: 1