apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    "helm.sh/hook": "post-install"
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: web
  remoteRead:
    - url: m3coordinator-persistent-cluster.monitoring:7201/api/v1/prom/remote/read
      readRecent: true
  remoteWrite:
    - url: m3coordinator-persistent-cluster.monitoring:7201/api/v1/prom/remote/write
