apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator-deployment: neon-cluster-operator
    operator-element: operator-instance
  name: operator
  namespace: neon-system
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: neon-cluster-operator
      operator-element: operator-instance
  template:
    metadata:
      labels:
        operator: neon-cluster-operator
        operator-element: operator-instance
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: neon-cluster-operator-webhook
        image: "{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          pullPolicy: {{ .Values.image.pullPolicy }}
        startupProbe:
          exec:
            command:
            - /health-check
            periodSeconds: 5
            timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - /health-check
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - /ready-check
            periodSeconds: 5
            initialDelaySeconds: 1
            timeoutSeconds: 1
        ports:
        - containerPort: 5000
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
