apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "etcd-m3db"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.2.13"
  pod:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: neonkube.io/mon.etcd
                operator: In
                values:
                - "true"
            topologyKey: kubernetes.io/hostname
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "2379"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      # The FSGroup is needed to let the etcd container access mounted volumes
      fsGroup: 1000
    persistentVolumeClaimSpec:
      storageClassName: "local-storage"
      accessModes:
      - ReadWriteOnce
      selector:
        matchLabels:
          etcd: monitoring
      resources:
        requests:
          storage: 1Gi