apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
metadata:
  name: {{ template "cortex.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "cortex.name" . }}
spec:
  ports:
  - port: {{ .Values.cortexConfig.server.http_listen_port }}
    name: http-cortex-server
    protocol: TCP
  clusterIP: None
  selector:
    app: {{ template "cortex.name" . }}
    release: {{ .Release.Name | quote }}