storage: # cluster level storage configuration and selection
  config:
    # The default and recommended storeType is dynamically set to bluestore for devices and filestore for directories.
    # Set the storeType explicitly only if it is required not to use the default.
    # storeType: bluestore
    #databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
    #journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
    osdsPerDevice: "1" # this value can be overridden at the node or device level
# Cluster level list of directories to use for storage. These values will be set for all nodes that have no `directories` set.
#    directories:
#    - path: /rook/storage-dir
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - name: "worker-0"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "xvdb"
      config:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: bluestore
    - name: "worker-1"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "xvdb"
      config:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: bluestore
    - name: "worker-2"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "xvdb"
      config:         # configuration can be specified at the node level which overrides the cluster level config
        storeType: bluestore


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
