apiVersion: operator.m3db.io/v1alpha1
kind: M3DBCluster
metadata:
  name: persistent-cluster
spec:
  image: quay.io/m3db/m3dbnode:latest
  replicationFactor: 3
  numberOfShards: 256
  isolationGroups:
  - name: group1
    numInstances: 1
    nodeAffinityTerms:
    - key: neonkube.io/physical.faultdomain
      values:
      - worker-0
  - name: group2
    numInstances: 1
    nodeAffinityTerms:
    - key: neonkube.io/physical.faultdomain
      values:
      - worker-1
  - name: group3
    numInstances: 1
    nodeAffinityTerms:
    - key: neonkube.io/physical.faultdomain
      values:
      - worker-2
  etcdEndpoints:
  - http://m3db-etcd-client.monitoring:2379
  podIdentityConfig:
    sources: []
  namespaces:
    - name: metrics-10s:2d
      preset: 10s:2d
  dataDirVolumeClaimTemplate:
    metadata:
      name: m3db-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "local-storage"
      selector:
        matchLabels:
          m3db: default
      resources:
        requests:
          storage: 1Gi
        limits:
          storage: 1Gi