name: wrt-jeff-small
datacenter: wrt-00
environment: development
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: xenserver
  vmHostUsername: $<<XENSERVER_USERNAME>>
  vmHostPassword: $<<XENSERVER_PASSWORD>>
  vmNamePrefix: jeff
  vmHosts:
  - name: WRT-00-XEN-00
    address: 10.100.128.85
  - name: WRT-00-XEN-01
    address: 10.100.128.91
  - name: WRT-00-XEN-02
    address: 10.100.128.97
  - name: WRT-00-XEN-03
    address: 10.100.128.103
  - name: WRT-00-XEN-04
    address: 10.100.128.109
  xenServer:
     snapshot: true
network:
  premiseSubnet: 10.100.0.0/16
  nodesSubnet: 10.100.32.0/22
nodeOptions:
   upgrade: none
   passwordLength: 20
nodes:
   master-0:
     role: master
     privateAddress: 10.100.32.0
     vmHost: WRT-00-XEN-00
     vmProcessors: 4
     vmMemory: 4GiB
     vmDisk: 32GiB
   worker-0:
     role: worker
     privateAddress: 10.100.32.10
     vmHost: WRT-00-XEN-01
     vmProcessors: 4
     vmMemory: 4GiB
     vmDisk: 32GiB
   worker-1:
     role: worker
     privateAddress: 10.100.32.11
     vmHost: WRT-00-XEN-03
     vmProcessors: 4
     vmMemory: 4GiB
     vmDisk: 32GiB
   worker-2:
     role: worker
     privateAddress: 10.100.32.12
     vmHost: WRT-00-XEN-04
     vmProcessors: 4
     vmMemory: 4GiB
     vmDisk: 32GiB
